title: Maak een hero image voor je website
hero_image: images/banner.png
description: Maak een grote afbeelding over de volledige breedte bovenaan je pagina, een zogenaamd hero image
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Maak een hero image voor je website
