title: Create a hero image for your webpage
hero_image: images/banner.png
description: Create a large full width image at the top of your page, called a hero image
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Create a hero image for your webpage
