---
title: Créer une image Hero pour ta page web
hero_image: images/banner.png
description: Crée une grande image en pleine largeur en haut de ta page, appelée une image Hero
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Créer une image Hero pour ta page web
